export type Character = {
  id: string;
  is_pc: boolean;
  owner_user_id: string | null;
  name: string;
  race: string | null;
  subrace: string | null;
  class: string | null;
  level: number | null;
  gender: string | null;
  age: number | null;
  alignment: string | null;
  background: string | null;
  personality_type: string | null;
  bio: string | null;
  short_pitch: string | null;
  portrait_url: string | null;
  created_at: string;
  updated_at: string;
  str_score: number | null;
  dex_score: number | null;
  con_score: number | null;
  int_score: number | null;
  wis_score: number | null;
  cha_score: number | null;
  portrait_status?: "pending" | "ready" | "error" | null;
  portrait_error?: string | null;
};
