services:
  db:
    image: postgres:15-alpine
    container_name: tavern_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tavern
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tavern_backend
    restart: always
    working_dir: /var/www
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:9000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: tavern
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    ports:
      - "9000:9000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tavern_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
