export type Character = {
  id: string;
  name: string;
  race: string;
  subrace?: string | null;
  class: string;
  level?: number | null;
  gender?: string | null;
  age?: number | null;
  alignment?: string | null;
  background?: string | null;
  personality_type?: string | null;
  bio?: string | null;
  short_pitch?: string | null;
  portrait_url?: string | null;
  str_score?: number | null;
  dex_score?: number | null;
  con_score?: number | null;
  int_score?: number | null;
  wis_score?: number | null;
  cha_score?: number | null;
};
